# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


services:
    calculator:
        class: AppBundle\Calculator

    invoice_generator:
        class: AppBundle\InvoiceGenerator
        arguments:
            - @calculator

    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]
        arguments:
            - { proximity: 2, previous_message: Anterior, next_message: Siguiente }